### ISSUE TITLE
Page Styling

### ISSUE THREAD

**Issue by SpeckiJ** [ling-js/skylax#46]
Currently there are major issues with styling:

 - Sidebar overflows when Metadata is displayed
 - Detailed Start-Time fields are offset
 - Save-sidebar Überschrift
 - Imprint
 - Save-Button not visible when on Homepage
 - bbox input no title
 - search string field not expanding properly (jump instead of smooth)
 - Datasets have no name (Just generic number)
 - Default selection for L2A Generation input (Currently: "Resolution 10m")
 - Offset between Min-Value and Max-Value fields
 - Capslock in L2A Metadata
 - Accordion open animation missing

To be continued

**Comment by Effizjens** [comment]
"Save-Button not visible when on Homepage" done with https://github.com/ling-js/skylax/commit/2bbee733fcfde1b204f3599d9baaef8ea56dfa57

**Comment by Thiemann96** [comment]
+ Button which removes all Bounding boxes and everything that is displayed on the map

**Comment by Thiemann96** [comment]
+ Overhaul of permalink site/tab

**Comment by Thiemann96** [comment]
+ Overhaul of Impressum page 
+ Maybe think of a new tab called "Team" , what do you think ?

**Comment by bkari02** [comment]
Styling issues that were cleared:

- Sidebar overflows when Metadata is displayed
- Detailed Start-Time fields are offset
- Save-sidebar Überschrift
- Imprint
- bbox input no title
- search string field not expanding properly (jump instead of smooth)
- Datasets have no name (Just generic number)
- Default selection for L2A Generation input (Currently: "Resolution 10m")
- Offset between Min-Value and Max-Value fields
- Capslock in L2A Metadata

**Comment by bkari02** [comment]
Still left are:

- Accordion open animation missing

No information about current status:

- Button which removes all Bounding boxes and everything that is displayed on the map
- Overhaul of permalink site/tab
- Overhaul of Impressum page
- Maybe think of a new tab called "Team" , what do you think ?

**Comment by Thiemann96** [comment]
Result page doesnt display given search parameters when you go to the 2nd page of the results
